In [1]:
from gensim.models import word2vec
import nltk
import pandas as pd 
import numpy as np
import re 
from sklearn.feature_extraction.text import TfidfVectorizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer


In [2]:
path = r"C:\Users\MY LAPTOP\Desktop\NLP\sentiment labelled sentences"

In [3]:
pd.read_csv(f"{path}\yelp_labelled.txt",delimiter ='\t',header=None)

0  1
0                             Wow... Loved this place.  1
1                                   Crust is not good.  0
2            Not tasty and the texture was just nasty.  0
3    Stopped by during the late May bank holiday of...  1
4    The selection on the menu was great and so wer...  1
..                                                 ... ..
995  I think food should have flavor and texture an...  0
996                           Appetite instantly gone.  0
997  Overall I was not impressed and would not go b...  0
998  The whole experience was underwhelming, and I ...  0
999  Then, as if I hadn't wasted enough of my life ...  0

[1000 rows x 2 columns]

In [4]:
websites = ['amazon_cells_labelled.txt','yelp_labelled.txt','imdb_labelled.txt']

In [5]:
df = pd.DataFrame()
for website in websites:
    website_df = pd.read_csv(f"{path}/{website}",delimiter ='\t',header = None)
    df = pd.concat([df,website_df],axis = 0)

In [6]:
df.columns = ['Review','Sentiment']

In [7]:
def text_preprocessor(doc):
    doc = doc.lower().strip()
    try:
        doc = doc.replace('.',". ")
        doc = doc.replace(',',", ")
        doc = doc.replace('!',"! ")
    except:
        pass
    doc = re.sub(r"[^a-z\s]","",doc) #to rmv space and anything not lower
    doc = [d.strip() for d in doc.split() if d not in stopwords]
    doc = " ".join(doc)
    return doc

In [8]:
stopwords = nltk.corpus.stopwords.words('English')

In [9]:
df['Cleaned_review']=df['Review'].apply(text_preprocessor)

In [10]:
sentences = [review.split() for review in df['Cleaned_review']] 

In [11]:
sentences

[['way', 'plug', 'us', 'unless', 'go', 'converter'],
 ['good', 'case', 'excellent', 'value'],
 ['great', 'jawbone'],
 ['tied',
  'charger',
  'conversations',
  'lasting',
  'minutes',
  'major',
  'problems'],
 ['mic', 'great'],
 ['jiggle', 'plug', 'get', 'line', 'right', 'get', 'decent', 'volume'],
 ['several',
  'dozen',
  'several',
  'hundred',
  'contacts',
  'imagine',
  'fun',
  'sending',
  'one',
  'one'],
 ['razr', 'owner', 'must'],
 ['needless', 'say', 'wasted', 'money'],
 ['waste', 'money', 'time'],
 ['sound', 'quality', 'great'],
 ['impressed', 'going', 'original', 'battery', 'extended', 'battery'],
 ['two',
  'seperated',
  'mere',
  'ft',
  'started',
  'notice',
  'excessive',
  'static',
  'garbled',
  'sound',
  'headset'],
 ['good', 'quality', 'though'],
 ['design', 'odd', 'ear', 'clip', 'comfortable'],
 ['highly', 'recommend', 'one', 'blue', 'tooth', 'phone'],
 ['advise', 'everyone', 'fooled'],
 ['far', 'good'],
 ['works', 'great'],
 ['clicks',
  'place',
  'way',


In [12]:
word_vec = word2vec.Word2Vec(sentences,epochs=10,sg = 1,vector_size =100,min_count =1,window =5,workers =1)

In [13]:
word_vec.wv.index_to_key #in decreasing order

['good',
 'great',
 'movie',
 'phone',
 'film',
 'one',
 'food',
 'like',
 'place',
 'time',
 'service',
 'really',
 'bad',
 'well',
 'dont',
 'would',
 'best',
 'ever',
 'even',
 'also',
 'back',
 'quality',
 'go',
 'love',
 'ive',
 'made',
 'im',
 'product',
 'get',
 'work',
 'nice',
 'better',
 'could',
 'excellent',
 'works',
 'never',
 'recommend',
 'much',
 'use',
 'sound',
 'think',
 'headset',
 'first',
 'battery',
 'way',
 'see',
 'pretty',
 'make',
 'didnt',
 'acting',
 'worst',
 'still',
 'got',
 'everything',
 'characters',
 'enough',
 'say',
 'two',
 'disappointed',
 'ear',
 'every',
 'little',
 'thing',
 'amazing',
 'price',
 'right',
 'going',
 'people',
 'minutes',
 'waste',
 'definitely',
 'terrible',
 'real',
 'case',
 'look',
 'money',
 'movies',
 'came',
 'new',
 'cant',
 'know',
 'experience',
 'friendly',
 'story',
 'many',
 'doesnt',
 'wont',
 'far',
 'poor',
 'used',
 'piece',
 'worth',
 'films',
 'plot',
 'nothing',
 'seen',
 'years',
 'life',
 'us',
 'wonderfu

In [14]:
words = word_vec.wv.index_to_key

In [15]:
word_vectors = word_vec.wv.vectors

In [16]:
word_vec.wv['good']

array([-1.31813973e-01,  2.35517532e-01,  5.61751574e-02,  5.24917692e-02,
       -1.12923831e-02, -3.90701085e-01,  1.13617569e-01,  3.75879765e-01,
       -1.38281867e-01, -2.00778380e-01, -2.77255867e-02, -3.81578505e-01,
       -1.73168082e-03,  2.31805928e-02,  2.17040637e-04, -1.88861519e-01,
        1.92678005e-01, -3.20991129e-01, -3.70989554e-02, -3.86444658e-01,
        2.06786558e-01,  1.35259479e-01,  2.07828715e-01, -1.57707687e-02,
       -1.18281394e-01, -3.33274081e-02, -3.89624387e-02, -1.56096160e-01,
       -1.78871393e-01, -4.86990362e-02,  2.90175408e-01,  2.77121775e-02,
       -1.98900551e-02, -1.86710417e-01,  1.43503826e-02,  2.99699366e-01,
        1.43147826e-01, -1.59250870e-01, -2.05992267e-01, -4.27150816e-01,
        7.16650262e-02, -2.80166835e-01,  2.18459452e-03, -4.74913903e-02,
        1.77965507e-01, -1.78578496e-01, -2.42276758e-01, -3.78776714e-02,
        1.00137211e-01,  1.91936508e-01,  4.15817536e-02, -1.81892201e-01,
       -3.88504490e-02,  

In [17]:
word_vectors.shape

(5105, 100)

In [18]:
vocab_size,vec_size = word_vectors.shape

In [19]:
word_vec.wv.most_similar('good')

[('nice', 0.9974833130836487),
 ('cheap', 0.9974064230918884),
 ('clean', 0.997371256351471),
 ('really', 0.9973599314689636),
 ('menu', 0.9973146319389343),
 ('bit', 0.9972962141036987),
 ('food', 0.9972341060638428),
 ('high', 0.9972167015075684),
 ('thats', 0.9971975088119507),
 ('bland', 0.9971833825111389)]

In [20]:
X= df['Cleaned_review']
y = df['Sentiment']

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 1)

In [23]:
X_train

579    due happening every call forced stop using hea...
178        weekly haunt definitely place come back every
829                                  really good product
452    colleague get great reception little expensive...
870         started review two stars im editing give one
                             ...                        
960    exchanged sony ericson za im pretty happy deci...
905        nearly good looking amazon picture makes look
96                                                  back
235                          one favorite purchases ever
61                       place receives stars appetizers
Name: Cleaned_review, Length: 2198, dtype: object

In [24]:
#convert x_train to numbers using tokenizer
#embedding layers is expecting positive numbers and tokenizer will give us positive num
#wordvec gives float

tokenizer = Tokenizer()
tokenizer.fit_on_texts(X_train)

In [25]:
tokenizer.word_index

{'good': 1,
 'great': 2,
 'phone': 3,
 'movie': 4,
 'film': 5,
 'one': 6,
 'like': 7,
 'place': 8,
 'food': 9,
 'time': 10,
 'service': 11,
 'really': 12,
 'well': 13,
 'bad': 14,
 'would': 15,
 'ever': 16,
 'best': 17,
 'dont': 18,
 'also': 19,
 'even': 20,
 'back': 21,
 'quality': 22,
 'go': 23,
 'ive': 24,
 'better': 25,
 'love': 26,
 'made': 27,
 'im': 28,
 'get': 29,
 'nice': 30,
 'product': 31,
 'work': 32,
 'use': 33,
 'much': 34,
 'works': 35,
 'never': 36,
 'could': 37,
 'recommend': 38,
 'way': 39,
 'think': 40,
 'headset': 41,
 'battery': 42,
 'sound': 43,
 'pretty': 44,
 'excellent': 45,
 'see': 46,
 'didnt': 47,
 'got': 48,
 'first': 49,
 'still': 50,
 'acting': 51,
 'case': 52,
 'make': 53,
 'look': 54,
 'little': 55,
 'ear': 56,
 'right': 57,
 'characters': 58,
 'worst': 59,
 'friendly': 60,
 'going': 61,
 'disappointed': 62,
 'came': 63,
 'two': 64,
 'say': 65,
 'amazing': 66,
 'everything': 67,
 'minutes': 68,
 'new': 69,
 'people': 70,
 'terrible': 71,
 'money': 72,
 

In [26]:
len(tokenizer.word_index)

4350

In [27]:
#to transform tokenizer to x_train andX_test
X_train = tokenizer.texts_to_sequences(X_train)
X_test = tokenizer.texts_to_sequences(X_test)

In [28]:
X_train

[[611, 1703, 82, 309, 1066, 764, 226, 41],
 [1704, 1705, 78, 8, 125, 21, 82],
 [12, 1, 31],
 [1706, 29, 2, 274, 55, 612, 201, 2],
 [275, 410, 64, 126, 28, 499, 95, 6],
 [500, 26, 501],
 [765, 15, 17, 39, 1067],
 [502, 1707, 72, 1708, 73],
 [613, 56, 1068, 1069, 17],
 [156],
 [1709, 42, 503, 1710, 227, 504],
 [1711, 60],
 [5, 27],
 [41, 1712, 1713, 96, 157],
 [17, 614, 505, 83],
 [2, 615, 1714, 1715, 766, 506, 310, 180, 33, 1716, 1717, 766, 1718, 767],
 [1719, 1070, 11, 228, 768, 158, 1720, 411, 86, 61, 21],
 [142],
 [1721, 1722, 1723, 17, 74, 229],
 [20, 1071, 616, 111, 1724, 504, 507, 1072, 1725, 1073, 230, 1726],
 [12, 103, 119, 311, 143, 57, 1074, 1727, 769, 355, 1728],
 [276, 1729, 127, 617, 32, 356, 1730, 128],
 [231, 159, 255],
 [11, 1, 357, 25],
 [30, 358],
 [11, 508, 20, 23, 770, 7, 7],
 [34, 65, 8, 509, 412, 66, 359, 62],
 [3, 771, 277],
 [86, 32, 57, 1731],
 [46, 127],
 [129, 618, 1732, 1733],
 [34, 181, 510, 360, 256, 1734, 1735],
 [1736, 361, 2, 1075, 1076, 614, 60, 144],
 

In [29]:
#pad every single senstences to have the same size using pad sequences
pad_sequences?


Signature:
pad_sequences(
    sequences,
    maxlen=None,
    dtype='int32',
    padding='pre',
    truncating='pre',
    value=0.0,
)
Docstring:
Pads sequences to the same length.

This function transforms a list (of length `num_samples`)
of sequences (lists of integers)
into a 2D Numpy array of shape `(num_samples, num_timesteps)`.
`num_timesteps` is either the `maxlen` argument if provided,
or the length of the longest sequence in the list.

Sequences that are shorter than `num_timesteps`
are padded with `value` until they are `num_timesteps` long.

Sequences longer than `num_timesteps` are truncated
so that they fit the desired length.

The position where padding or truncation happens is determined by
the arguments `padding` and `truncating`, respectively.
Pre-padding or removing values from the beginning of the sequence is the
default.

>>> sequence = [[1], [2, 3], [4, 5, 6]]
>>> tf.keras.preprocessing.sequence.pad_sequences(sequence)
array([[0, 0, 1],
       [0, 2, 3],
       [4,

In [30]:
X_train = pad_sequences(X_train,maxlen = vec_size,padding = 'post')
X_test = pad_sequences(X_test,maxlen = vec_size,padding = 'post')

The pad_sequences() function is used to pad or truncate sequences to a fixed length, which is specified by the maxlen parameter. In this case, X_train and X_test are likely arrays of sequences, such as sentences or documents. The vec_size parameter represents the maximum length of the sequences after padding or truncation.

Padding is added to the end of sequences that are shorter than vec_size, while truncation removes characters from the end of sequences that are longer than vec_size. The padding parameter specifies whether to pad sequences with zeros at the beginning (padding='pre') or at the end (padding='post').

In [31]:
X_train

array([[ 611, 1703,   82, ...,    0,    0,    0],
       [1704, 1705,   78, ...,    0,    0,    0],
       [  12,    1,   31, ...,    0,    0,    0],
       ...,
       [  21,    0,    0, ...,    0,    0,    0],
       [   6,  524, 4349, ...,    0,    0,    0],
       [   8, 4350,  126, ...,    0,    0,    0]])

In [32]:
X_train[0]

array([ 611, 1703,   82,  309, 1066,  764,  226,   41,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0])

In [ ]:
#wordvec as weight

In [33]:
token_size = len(tokenizer.word_index) + 1

Here's a breakdown of the code:

tokenizer.word_index is a dictionary that maps each unique word in the tokenizer's vocabulary to a unique integer index.
len(tokenizer.word_index) returns the number of unique words in the tokenizer's vocabulary.
Adding 1 to this number accounts for an extra index that is reserved for out-of-vocabulary (OOV) words.
token_size is the final result, which represents the total number of unique tokens (i.e., words and OOV tokens) in the tokenizer's vocabulary.
By calculating the token size, you can use it as the input size for a neural network's embedding layer or as the output size for a neural network's final layer, depending on the specific use case.

In [34]:
token_size

4351

In [35]:
embedding_matrix = np.zeros((token_size,vec_size))
for word,index in tokenizer.word_index.items():
    if word in word_vec.wv:
        embedding_matrix[index] = word_vec.wv[word]

In [36]:
embedding_matrix

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-1.31813973e-01,  2.35517532e-01,  5.61751574e-02, ...,
        -2.65085220e-01,  9.69008207e-02, -1.19537523e-03],
       [-1.44251645e-01,  2.39837125e-01,  4.84004579e-02, ...,
        -2.61130333e-01,  8.26922581e-02, -1.23599982e-02],
       ...,
       [-3.00984289e-02,  4.54902314e-02,  1.12961949e-04, ...,
        -4.97273654e-02,  2.01678947e-02, -4.32601338e-03],
       [-8.49220529e-03,  1.92739889e-02,  1.14703467e-02, ...,
        -1.80626754e-02,  7.72192609e-03,  2.33535562e-03],
       [-8.44088383e-03,  1.72328185e-02,  9.68292169e-03, ...,
        -2.36082468e-02,  9.68559645e-03, -4.17269813e-03]])

# RNN

In [37]:
from tensorflow.keras.layers import Embedding, Dense, Dropout, LSTM, SimpleRNN
from tensorflow.keras.models import Sequential

In [38]:
model = Sequential()
model.add(Embedding(input_dim = token_size,output_dim = vec_size,input_length = vec_size,
                    weights = [embedding_matrix]))
model.add(LSTM(units=256,dropout = 0.3,recurrent_dropout = 0.2,return_sequences = True))
model.add(LSTM(units=128,return_sequences = True))
model.add(Flatten())
model.add(Dense(units=1,activation = 'sigmoid'))

This code block appears to be creating a Sequential neural network model for text classification or sentiment analysis.

Here's a breakdown of the code:

model is initialized as a Sequential model, which means that each layer is added sequentially on top of the previous layer.
The first layer is an Embedding layer, which takes as input the token_size, vec_size, and input_length. token_size is the number of unique tokens in the vocabulary, vec_size is the dimensionality of the pre-trained word vectors, and input_length is the length of the input sequence. The weights parameter is set to embedding_matrix, which contains the pre-trained word vectors. This layer converts the input sequence of integers into dense vectors using the pre-trained word embeddings.
The second and third layers are LSTM (Long Short-Term Memory) layers, which are a type of recurrent neural network (RNN) that can capture long-term dependencies in sequential data. The first LSTM layer has 256 units and a dropout of 0.3, which helps prevent overfitting. It also has return_sequences = True, which means that it returns the full sequence of outputs rather than just the last output. The second LSTM layer has 128 units and return_sequences = False, which means that it only returns the final output.
The fourth layer is a Dense layer with a single output unit and a sigmoid activation function, which produces a binary classification output (0 or 1) representing the sentiment of the input text.
By creating this model, you can train it on a labeled dataset of text and sentiment labels using a suitable optimizer and loss function. Once trained, the model can be used to predict the sentiment of new text inputs

In [55]:
Embedding?

In [39]:
y.value_counts()

1    1386
0    1362
Name: Sentiment, dtype: int64

In [40]:
model.compile(loss='binary_crossentropy',optimizer = 'adam',metrics =['accuracy'])

In [41]:
model.fit(X_train,y_train,epochs= 30,validation_split = 0.15,verbose = 1)

c:\Users\MY LAPTOP\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\data_adapter.py:1696: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  return t[start:end]


Epoch 1/30
59/59 [==============================] - 49s 731ms/step - loss: 0.6941 - accuracy: 0.4732 - val_loss: 0.6945 - val_accuracy: 0.4727
Epoch 2/30
59/59 [==============================] - 57s 960ms/step - loss: 0.6934 - accuracy: 0.5037 - val_loss: 0.6935 - val_accuracy: 0.4727
Epoch 3/30
59/59 [==============================] - 54s 911ms/step - loss: 0.6932 - accuracy: 0.5054 - val_loss: 0.6937 - val_accuracy: 0.4727
Epoch 4/30
59/59 [==============================] - 55s 925ms/step - loss: 0.6932 - accuracy: 0.5059 - val_loss: 0.6938 - val_accuracy: 0.4727
Epoch 5/30
59/59 [==============================] - 55s 928ms/step - loss: 0.6932 - accuracy: 0.5064 - val_loss: 0.6936 - val_accuracy: 0.4727
Epoch 6/30
59/59 [==============================] - 56s 943ms/step - loss: 0.6932 - accuracy: 0.4989 - val_loss: 0.6935 - val_accuracy: 0.4727
Epoch 7/30
59/59 [==============================] - 54s 918ms/step - loss: 0.6935 - accuracy: 0.4898 - val_loss: 0.6959 - val_accuracy: 0.4727

In [ ]:
#doesnt outperformd Ml we used=sol:huge amount of data to train on
#use google pretrained model